In [1]:
import numpy as np

In [2]:
x = np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
print(x)
print(type(x))
print(x.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
float64


In [7]:
x = np.full((2,3),5)

print(x)
print()
print(x.shape)
print(type(x))
print(x.dtype)

[[5. 5. 5.]
 [5. 5. 5.]]

(2, 3)
<class 'numpy.ndarray'>
float64


In [8]:
x = np.eye(5) # numpy array of an identity matrix
print(x)

print(x.shape)
print(type(x))
print(x.dtype)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
<class 'numpy.ndarray'>
float64


In [10]:
# create a diagonal matrix 
x = np.diag([10,20,30,50])

print(x,'\n')
print(x.shape)
print(type(x))
print(x.dtype)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]] 

(4, 4)
<class 'numpy.ndarray'>
int64


In [11]:
x = np.arange(10)

print(x)
print(x.shape)
print(type(x))
print(x.dtype)

[0 1 2 3 4 5 6 7 8 9]
(10,)
<class 'numpy.ndarray'>
int64


In [12]:
x = np.arange(4,10)
x

array([4, 5, 6, 7, 8, 9])

In [13]:
x = np.arange(1,14,3)
x

array([ 1,  4,  7, 10, 13])

In [15]:
x = np.linspace(0,25,10) # 25 is inclusive here. there are other arugments in linspace
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [16]:
x = np.arange(20)

print('original x', x)

x = np.reshape(x,(4,5))
print('reshaped x',x)

print(x.shape)
print(type(x))
print(x.dtype)

original x [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
reshaped x [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
<class 'numpy.ndarray'>
int64


In [17]:
# numpy arrays are like numpy attributes: both can be called using the "."
x = np.arange(20).reshape(4,5) 
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [20]:
x = np.linspace(0,50,10,endpoint=False).reshape(5,2)

print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [21]:
# 3x3 numpy random array, elements belong to (0.0,1.0]
x = np.random.random((3,3))
print(x)

[[0.22058183 0.56536229 0.99878656]
 [0.65805444 0.21077864 0.61213907]
 [0.16292012 0.88184285 0.74574613]]


In [32]:
x = np.random.randint(4,15,size=(3,2))
print(x)

[[ 7 14]
 [ 6  6]
 [ 4  5]]


In [47]:
# create a numpy array of size 5x5, mean = 0, stdv = 1 (normal distribution)
x = np.random.normal(0,1,size=(5,5))
print(x)

[[ 0.08752891 -0.51416446 -0.01153212  0.17928685  0.00756673]
 [ 0.79177427  1.48869499 -1.21830071  0.85164042 -0.53767476]
 [ 1.51589081  0.77328445  1.25559824  0.34158211 -0.01570917]
 [-0.21150829  0.92639404 -0.99254501 -0.93134591 -2.05917832]
 [-0.25236415  0.12207104  1.61347146  0.30692683  0.78613064]]


In [48]:
print(x.shape)
print(type(x))
print(x.dtype)
print(x.mean())
print(x.max()) # to find the min element
print(x.min()) # to find the max element
print((x<0).sum()) # to find the sum of the negative elements
print((x>0))

(5, 5)
<class 'numpy.ndarray'>
float64
0.17214075471712392
1.6134714583317507
-2.059178321214203
10
[[ True False False  True  True]
 [ True  True False  True False]
 [ True  True  True  True False]
 [False  True False False False]
 [False  True  True  True  True]]


In [49]:
(x<0)

array([[False,  True,  True, False, False],
       [False, False,  True, False,  True],
       [False, False, False, False,  True],
       [ True, False,  True,  True,  True],
       [ True, False, False, False, False]])

In [53]:
print((x<0))

[[False  True  True False False]
 [False False  True False  True]
 [False False False False  True]
 [ True False  True  True  True]
 [ True False False False False]]


In [56]:
sum(x<0) # how many negative elements are there per column

array([2, 1, 3, 1, 3])