In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [3]:
y = np.array([5.5,6.5,7.5,8.5])
print(y)

[5.5 6.5 7.5 8.5]


In [5]:
print(x+y)

[ 6.5  8.5 10.5 12.5]


In [6]:
print(np.add(x,y))

[ 6.5  8.5 10.5 12.5]


In [7]:
print(x-y)

[-4.5 -4.5 -4.5 -4.5]


In [8]:
print(np.subtract(x,y))

[-4.5 -4.5 -4.5 -4.5]


In [9]:
print(x*y)

[ 5.5 13.  22.5 34. ]


In [10]:
print(np.multiply(x,y))

[ 5.5 13.  22.5 34. ]


In [11]:
print(x/y)

[0.18181818 0.30769231 0.4        0.47058824]


In [12]:
print(np.divide(x,y))

[0.18181818 0.30769231 0.4        0.47058824]


In [14]:
# to work with rank 2 arrays, arrays must be of the same shape
# or broadcastable
x = x.reshape(2,2)
y = y.reshape(2,2)
print(x,'\n')
print(y)

[[1 2]
 [3 4]] 

[[5.5 6.5]
 [7.5 8.5]]


In [15]:
print(x+y)

[[ 6.5  8.5]
 [10.5 12.5]]


In [16]:
print(np.add(x,y))

[[ 6.5  8.5]
 [10.5 12.5]]


In [17]:
print(x-y)

[[-4.5 -4.5]
 [-4.5 -4.5]]


In [18]:
print(np.subtract(x,y))

[[-4.5 -4.5]
 [-4.5 -4.5]]


In [19]:
print(x*y)

[[ 5.5 13. ]
 [22.5 34. ]]


In [20]:
print(np.multiply(x,y))

[[ 5.5 13. ]
 [22.5 34. ]]


In [21]:
print(x/y)

[[0.18181818 0.30769231]
 [0.4        0.47058824]]


In [22]:
print(np.divide(x,y))

[[0.18181818 0.30769231]
 [0.4        0.47058824]]


In [23]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [24]:
print(x)

[[1 2]
 [3 4]]


In [25]:
x = x.reshape(4,)
print(x)

[1 2 3 4]


In [26]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [29]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [33]:
print(np.power(x,2))

[ 1  4  9 16]


In [34]:
x = x.reshape(2,2)
print(x)

[[1 2]
 [3 4]]


In [35]:
print(x.mean())

2.5


In [37]:
print(x.mean(axis=0))

[2. 3.]


In [38]:
print(x.mean(axis=1))

[1.5 3.5]


In [40]:
print(x.sum())

10


In [44]:
print(x.sum(axis=0))

[4 6]


In [45]:
print(x.sum(axis=1))

[3 7]


In [47]:
print(x.std())

1.118033988749895


In [48]:
print(x.std(axis=0))

[1. 1.]


In [49]:
print(x.std(axis=1))

[0.5 0.5]


In [51]:
print(np.median(x))

2.5


In [52]:
print(np.median(x,axis=0))

[2. 3.]


In [53]:
print(np.median(x,axis=1))

[1.5 3.5]


In [54]:
print(np.max(x))

4


In [55]:
print(np.max(x,axis=0))

[3 4]


In [56]:
print(np.max(x,axis=1))

[2 4]


In [58]:
print(x.min())

1


In [59]:
print(x.min(axis=0))

[1 2]


In [60]:
print(x.min(axis=1))

[1 3]


In [61]:
print(x)

[[1 2]
 [3 4]]


In [62]:
print(3*x)

[[ 3  6]
 [ 9 12]]


In [63]:
print(x+3)

[[4 5]
 [6 7]]


In [64]:
print(x-3)

[[-2 -1]
 [ 0  1]]


In [65]:
print(x/3)

[[0.33333333 0.66666667]
 [1.         1.33333333]]


In [66]:
x = np.array([1,2,3])
y = np.arange(1,10).reshape(3,3)
print(x,'\n')
print(y)

[1 2 3] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
z = np.array([1,2,3]).reshape(3,1)
print(z)

[[1]
 [2]
 [3]]


In [68]:
print(x+y)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [69]:
print(y+z)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [70]:
X = np.ones((4,4))
print(X)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [71]:
print(X*np.arange(1,5))

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [73]:
print(np.arange(1,5))

[1 2 3 4]


In [74]:
print(X)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [77]:
print(X*[0,1,2,3])

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
