In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
print(x)

[1 2 3]


In [4]:
x.ndim

1

In [5]:
y = np.array([[1,2,3],[4,5,6],[6,7,8]])
y.ndim

2

In [7]:
z = np.zeros((2,3,4))
z.ndim

3

In [9]:
x = np.array([1,2,3,4,5])
print(x)
print('dimensions', x.shape)
print('x is an object of datatype', type(x))
print('the elements of x are of datatype',x.dtype) # all elements of the array must be the same

[1 2 3 4 5]
dimensions (5,)
x is an object of datatype <class 'numpy.ndarray'>
the elements of x are of datatype int64


In [10]:
x = np.array(['Hello','World'])

print(x)
print('dimensions', x.shape)
print('x is an object of datatype', type(x))
print('the elements of x are of datatype',x.dtype)

['Hello' 'World']
dimensions (2,)
x is an object of datatype <class 'numpy.ndarray'>
the elements of x are of datatype <U5


In [11]:
x = np.array([1,2,'World'])

print(x)
print('dimensions', x.shape)
print('x is an object of datatype', type(x))
print('the elements of x are of datatype',x.dtype) # all elements are strings

['1' '2' 'World']
dimensions (3,)
x is an object of datatype <class 'numpy.ndarray'>
the elements of x are of datatype <U21


In [12]:
x = np.array([1,2,3])
y = np.array([1.0,2.0,3.0])
z = np.array([1,2.0,3]) # all are float, upcasting

print(x.dtype)
print(y.dtype)
print(z.dtype)

int64
float64
float64


In [13]:
x = np.array([1.5,2.2,3.7,4.0,5.9],dtype=np.int64) # assigning a data type
print(x)
print(x.dtype)

[1 2 3 4 5]
int64


In [14]:
y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

print(y)
print(y.shape)
print(y.size)
print(type(y))
print(y.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
12
<class 'numpy.ndarray'>
int64


In [15]:
x = np.array([1,2,3,4,5])
np.save('np_array',x)

In [17]:
y = np.load('np_array.npy') #.npy is the extension

print(y)

[1 2 3 4 5]
