In [1]:
import numpy as np

In [2]:
x = np.arange(0,20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
z = x[1:,2:]
print(z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [5]:
y = np.array([[2,3,4],[7,8,9],[12,13,14]])
print(y)

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [6]:
v = y[2,:]
print(v)

[12 13 14]


In [7]:
q = x[:,2]
print(q)

[ 2  7 12 17]


In [9]:
r = x[:,2:3] # to print a rank 2 ndarray
print(r)

[[ 2]
 [ 7]
 [12]
 [17]]


In [13]:
## slicing and copying 
x = np.arange(0,20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
z = x[1:,2:]
print(z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [15]:
z[2,2]=555
print(x) # x also changes

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]


In [17]:
x = np.arange(0,20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [18]:
z = np.copy(x[1:,2:])
z[2,2]=555
print(z)

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]


In [19]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [20]:
w = x[1:,2:].copy()
w[2,2]=444
print(w)

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


In [21]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [23]:
x = np.arange(20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [24]:
indices = np.array([1,3])
y = x[indices,:]
print(y)

[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [25]:
z = x[:,indices]
print(z)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [33]:
x = np.arange(0,25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [34]:
z = np.diag(x)
print(z)

[ 0  6 12 18 24]


In [35]:
y = np.diag(x,k=1)
print(y)

[ 1  7 13 19]


In [40]:
w = np.diag(x,k=-3)
print(w)

[15 21]


In [41]:
x = np.array([[1,2,3],[5,2,8],[1,2,3]])
print(x)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [44]:
print(np.unique(x))

[1 2 3 5 8]
