In [1]:
import numpy as np

In [2]:
# boolean indexing 
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
print(x[x>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [5]:
print(x[x<=7])

[0 1 2 3 4 5 6 7]


In [9]:
print(x[(x>10) & (x<17)])

[11 12 13 14 15 16]


In [10]:
x[(x<17) & (x>10)]=-1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [13]:
# set operations 
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
print(x)
print(y)
print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[1 2 3 4 5]
[6 7 2 8 4]
[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [34]:
x = np.random.randint(0,11,size=(10,))
print(x)

[7 6 7 7 4 8 2 9 2 0]


In [43]:
print(np.sort(x))
y = np.sort(x) 
print(y)
y = np.append(y,1)
print(y)
print(x)

[0 2 2 4 6 7 7 7 8 9]
[0 2 2 4 6 7 7 7 8 9]
[0 2 2 4 6 7 7 7 8 9 1]
[0 2 2 4 6 7 7 7 8 9]


In [44]:
print(x)

[0 2 2 4 6 7 7 7 8 9]


In [45]:
print(x.sort())

None


In [46]:
print(x)

[0 2 2 4 6 7 7 7 8 9]


In [47]:
print(np.unique(x))

[0 2 4 6 7 8 9]


In [51]:
x = np.random.randint(1,11,size=(5,5))
print(x)

[[ 5  7  7  2  5]
 [ 8  2  2  8  7]
 [ 2  3  4  8  2]
 [ 7  1  5  2  4]
 [ 6  1  6  4 10]]


In [52]:
print(np.sort(x,axis=0))

[[ 2  1  2  2  2]
 [ 5  1  4  2  4]
 [ 6  2  5  4  5]
 [ 7  3  6  8  7]
 [ 8  7  7  8 10]]


In [54]:
print(np.sort(x,axis=1))

[[ 2  5  5  7  7]
 [ 2  2  7  8  8]
 [ 2  2  3  4  8]
 [ 1  2  4  5  7]
 [ 1  4  6  6 10]]
