In [1]:
import numpy as np

In [4]:
x = np.array([1,2,3,4,5])

print(x)
print(x[0])
print(x[4])
print(x[-5])
print(x[-1])

[1 2 3 4 5]
1
5
1
5


In [5]:
print(x)


[1 2 3 4 5]


In [6]:
x[3] = 10
x

array([ 1,  2,  3, 10,  5])

In [10]:
x = np.array([[1,2,3],[4,5,6]])

print(x)
print(x[0,0]) # accessing a rank 2 ndarray
print(x[1,2])

[[1 2 3]
 [4 5 6]]
1
6


In [11]:
print(x,'\n')
x[0,0]=20
print(x)

[[1 2 3]
 [4 5 6]] 

[[20  2  3]
 [ 4  5  6]]


In [13]:
x = np.array([1,2,3,4,5])
print(x,'\n')
x = np.delete(x,[0,4]) # list of indices 
print(x)



[1 2 3 4 5] 

[2 3 4]


In [16]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y,'\n')
w = np.delete(y,0,axis=0) # second argument: first row
print(w)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[4 5 6]
 [7 8 9]]


In [18]:
z = np.delete(y,[0,2],axis=1)# second argument: first and last row
print(z)

[[2]
 [5]
 [8]]


In [22]:
x = np.array([1,2,3,4,5])
print(x)
x = np.append(x,6)
print(x)
x = np.append(x,[7,8])
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]


In [27]:
y = np.array([[1,2,3],[4,5,6]])
print(y,'\n')
v = np.append(y,[[7,8,9]],axis=0)
print(v)

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
q = np.append(y,[[9],[10]],axis=1) # note the the list
print(q)

[[ 1  2  3  9]
 [ 4  5  6 10]]


In [32]:
x = np.array([1,2,5,6,7])
print(x)

[1 2 5 6 7]


In [37]:
y = np.array([[1,2,3],[7,8,9]])
print(y)

[[1 2 3]
 [7 8 9]]


In [40]:
w = np.insert(y,1,[4,5,6],axis=0)
print(w)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
w = np.insert(y,1,5,axis=1)
print(w)

[[1 5 2 3]
 [7 5 8 9]]


In [41]:
x = np.array([1,2])
print(x)

[1 2]


In [43]:
y = np.array([[3,4],[5,6]])
print(y)

[[3 4]
 [5 6]]


In [44]:
z = np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [48]:
w = np.hstack((y,x.reshape(2,1)))
print(w)

[[3 4 1]
 [5 6 2]]
